### ISSUE TITLE
spots card list

### ISSUE THREAD

**Issue by FelineHuhn** [FelineHuhn/capstone-project-parenthood#1]
## Value Proposition

**As a** user
**I want to** see a list of spots
**so that** I can browse spots where I can go with children

## Description

![Image](https://user-images.githubusercontent.com/112863528/201713899-7a632ff2-cab3-454a-a6f5-85931381dca5.png)

## Acceptance Criteria

- [x] spots are displayed as cards in a list
- [x] spots are sorted alphabetically by spot-name
- [x] the headline is "ParentHood Spots"
- [x] the list-cards include the spot-category, the spot-name and a placeholder image

## Tasks

- [x] create feature branch
- [x] add headline
- [x] create `SpotCard` Component
     - [x] add placeholder image
     - [x] add category
     - [x] add name
- [x] create spots mock array
- [x] use `SpotCard` Component to display spots mock array

## Complexity

M
