### ISSUE TITLE
favorite spots

### ISSUE THREAD

**Issue by FelineHuhn** [FelineHuhn/capstone-project-parenthood#11]
## Value Proposition

**As a** user
**I want to** highlight and save my favorite spots separate 
**so that** I have all my favorite spots collected in one place 

## Description

![Image](https://user-images.githubusercontent.com/112863528/203278183-d8691881-b62f-45d0-a073-95b1824fe4ad.png)

## Acceptance criteria
- [x] the spot card has a button to mark the spot as favorite
    - [x] the mark button shows a heart icon 
    - [x] by clicking the favorite button the heart will be toggle between marked and unmarked
- [x] the application has a favorites page
    - [x] the favorites page has the headline "Lieblings Spots"
    - [x] the favorites page displays only as favorite marked spots
- [x] the navigation has a heart icon
    - [x] by clicking the heart icon the user will navigate to the favorites page

## Tasks
- [x] create feature branch
- [x] create `favorites` page
    - [x] add headline "Lieblings Spots"
- [x] add heart icon as Link
    - [x] add logic to link to favorites page on click
- [x] add heart icon as toggle mark button
- [x] add logic to display only as favorite marked spots cards on favorites page
    

## Complexity Estimation
M

**Comment by gaiisay** [comment]
Einwandfrei
