### ISSUE TITLE
spots category filter

### ISSUE THREAD

**Issue by FelineHuhn** [FelineHuhn/capstone-project-parenthood#13]
## Value Proposition

**As a** user
**I want to** be able to filter the spots by their category, 
**so that** I only see spots that are relevant for a visit with my children

## Description

![Image](https://user-images.githubusercontent.com/112863528/203519323-6a0d99e1-dc5a-4495-9f0e-ba2a4a0849d7.png)

## Acceptance criteria
- [x] the spots page has an optional filter selection above the spot cards
    - [x] by selecting a filter option the spots page will display only the spots that correspond to the filter 

## Tasks
- [x] create feature branch
- [x] add a filter selection to spots page
    - [x] add logic to display only the spots filtered by selected category on spots page 

## Complexity Estimation
M

**Comment by EugenMoser** [comment]
short and clearly. Top

**Comment by ahohnsen** [comment]
One tiny suggestion:

I would add an option "all" or similar, so the user can see all available spots. 🙂
