### ISSUE TITLE
photo upload

### ISSUE THREAD

**Issue by FelineHuhn** [FelineHuhn/capstone-project-parenthood#14]
## Value Proposition

**As a** user
**I want to** be able to upload a photo to a spot card 
**so that** I can see how a spot looks like

## Description

![Image](https://user-images.githubusercontent.com/112863528/203534200-fbb9addb-2524-41ee-a94b-44f253a4d87d.png)

## Acceptance criteria
- [x] the create page has an optional photo upload
- [x] the edit page has an optional photo upload
- [x] the uploaded photo will be displayed on the related spot card instead of the placeholder photo  

## Tasks
- [x] create feature branch
- [x] add a photo upload icon to the `SpotForm` component
    - [x] add logic to upload a photo by clicking the upload icon  
    - [x] add logic to display the uploaded photo on the spot card 

## Complexity Estimation
L
