### ISSUE TITLE
spot card details

### ISSUE THREAD

**Issue by FelineHuhn** [FelineHuhn/capstone-project-parenthood#2]
## Value Proposition

**As a** user
**I want to** see details for each of the cards
**so that** I am able to make a better decision if I want to visit that spot

## Description

![Image](https://user-images.githubusercontent.com/112863528/201714030-082bfe9d-d22b-4d12-9229-0a425b963de8.png)
![Image](https://user-images.githubusercontent.com/112863528/201714031-6f21cfe3-d847-4584-9499-60594ef521d8.png)

## Acceptance Criteria

- [x] the spot card has a "Details" button
- [x] by clicking the "Details" button the details get displayed below the card
- [x] the headline of the details section is "Details"
- [x] the details section has following subsections: "Adresse", "Wetterempfehlung", "Altersempfehlung", "Tags", "Weitere Infos"
- [x] the details section has a "Schließen" button
- [x] by clicking the "Schließen" button the details section will disappear

## Tasks

- [x] create feature branch 
- [x] add "Details" button to `SpotCard` Component
    - [x] add logic to show details section on button
      click: 
         - [x] headline "Details:"
         - [x] "Adresse"
         - [x] "Wetterempfehlung"
         - [x] "Altersempfehlung"
         - [x] "Tags"
         - [x] "Weitere Infos"
         - [x] "Schließen" button 
            - [x] add logic to hide details section on 
              button click 

## Complexity

L

**Comment by ahohnsen** [comment]
Hey Feline,

Love your wireframe 😍
One little thing: Please have a look again at the last part of your value proposition. What is the value for the user to see the details of a spot? Maybe to be able to make a better decision if he/she wants to visit that spot.
