### ISSUE TITLE
landing page

### ISSUE THREAD

**Issue by FelineHuhn** [FelineHuhn/capstone-project-parenthood#21]
## Value Proposition

**As a** user
**I want to** see a welcome message when I start the app
**so that** I know immediately which app I'm using

## Description

![Image](https://user-images.githubusercontent.com/112863528/204780784-6097a738-d817-49bd-9e70-1aba8ad2b17b.png)

## Acceptance criteria
- [x] when the user starts the app, a landing page should be shown
- [x] the landing page has a photo as background 
- [x] the landing page has a welcome message 
  - [x] the welcome message includes the app title
- [x] the landing page has a link which navigates to the spots page

## Tasks
- [x] open feature branch
- [x] use the index.js as landingpage
- [x] add an image as background
- [x] add a welcome message
- [x] add a link and add logic to navigate to spots page 

## Complexity Estimation
M

**Comment by BucherLara** [comment]
Huhu Feline, the idea is really nice! My first thought was: the message "zu den Spots" is not clear enough for me, maybe you can add "Spiel-spots"  or a little text message to make it clearer.
