### ISSUE TITLE
add new spot card

### ISSUE THREAD

**Issue by FelineHuhn** [FelineHuhn/capstone-project-parenthood#3]
## Value Proposition

**As a** user
**I want to** add a new card
**so that** I can share my spots

## Description

![Image](https://user-images.githubusercontent.com/112863528/201751297-ba8badfc-e776-4e80-9f8a-9045e0af2e57.png)
![Image](https://user-images.githubusercontent.com/112863528/201695339-ab2c0750-d3bd-4548-8d3a-14981841036b.png)
![Image](https://user-images.githubusercontent.com/112863528/201871183-1c6cdebc-0b9e-4c30-beae-1a735ae168a5.png)

## Acceptance Criteria

- [x] the Spots Page has a "Neuen ParentHood Spot hinzufügen" button below the last displayed card
- [x] by clicking the "Neuen ParentHood Spot hinzufügen" button a form get displayed below the button
  - [x] the headline of the form is "Neuen ParentHood Spot hinzufügen"
  - [x] the form has a required "Kategorie: dropdown selection
  - [x] the form has a required "Name:" text input field 
  - [x] the form has a required "Adresse:" text input field
  - [x] the form has a optional "Tags:" text input field 
  - [x] the form has a optional "Wetterempfehlung:" multiple-choice checkbox
  - [x] the form has a optional "Altersempfehlung:" multiple-choice checkbox
  - [x] the form has a optional "Weitere Infos:" text input field
  - [x] the form has a "Spot erstellen" submit button
    - [x] by clicking the "Spot erstellen" submit button the form will disappear and the new card will be displayed as card from the card list

## Tasks

- [x] create feature branch
- [x] create `CreateSpot` Component
  - [x] add form with
    - [x] headline "Neuen ParentHood Spot hinzufügen:"
    - [x] required select "Kategorie:"
    - [x] required text input "Name:"
    - [x] required text input "Adresse:"
    - [x] optional text input "Tags:" 
    - [x] optional checkbox "Wetterempfehlung:"
    - [x] optional checkbox "Altersempfehlung:" 
    - [x] optional textarea "Weitere Infos:" 
    - [x] submit button "Spot erstellen"
      - [x] add logic to hide and clear form and add new card to card list on button click
  - [x] add "Neuen ParentHood Spot hinzufügen" button to the end of the card list
    - [x] add logic to display `CreateSpot` Component right below on button click

## Complexity

L

**Comment by JulianHrt** [comment]
Hi Feline, very nice detailed Tasks and wireframes.
