### ISSUE TITLE
delete spot card

### ISSUE THREAD

**Issue by FelineHuhn** [FelineHuhn/capstone-project-parenthood#4]
## Value Proposition

**As a** user
**I want to** have the option to delete a spot card
**so that** I can remove spots from the list

## Description

![Image](https://user-images.githubusercontent.com/112863528/201752841-6a12d51d-2267-4032-8f6f-7ddf76a58ed3.png)
![Image](https://user-images.githubusercontent.com/112863528/202138215-3c83cd39-56a3-4c21-97a5-86528ea700bc.png)

## Acceptance criteria

- [x] the details section has a delete button
    - [x] the delete button shows a trash icon 
    - [x] by clicking the delete button a pop-up will be displayed, which ask the user, if he's sure to delete the spot card
      - [x] the pop up has a delete button and a cancel button

## Tasks

- [x] create feature branch
- [x] add delete button to details section
   - [x] add trash icon as button text
   - [x] add logic to open a delete modal on button click 
     - [x] add delete button and cancel button to the delete modal 
       - [x] add logic to delete specific card on delete button click or close the delete modal on cancel button click

## Complexity

L

**Comment by ahohnsen** [comment]
Hey Feline,

A little suggestion: Maybe it would be nice if a modal opens, where the user can confirm the deletion of the card before it really gets deleted. :)
