### ISSUE TITLE
edit spot card

### ISSUE THREAD

**Issue by FelineHuhn** [FelineHuhn/capstone-project-parenthood#5]
## Value Proposition

**As a** user
**I want to** have the option to edit a spot card
**so that** I can change the information of a spot

## Description

![Image](https://user-images.githubusercontent.com/112863528/201752976-ac435e95-a1b4-4bed-8970-c28d124d7829.png)
![Image](https://user-images.githubusercontent.com/112863528/201697663-f02d43e8-bdd0-4a82-889e-0bd8f04a9420.png)

## Acceptance Criteria

- [x] the details section has an edit button
  - [x] the edit button shows an edit icon 
  - [x] by clicking the edit button the create card form will be displayed with the already filled information
    - [x] the form has a "Spot aktualisieren" button
    - [x] by clicking the "Spot aktualisieren" button the form will disappear and the card will be displayed with the updated information

## Tasks

- [x] create feature branch
- [x] add edit button to details section
  - [x] add edit icon as button text
  - [x] write logic to display the `CreateSpot` Component form with prefilled spot information in the input fields on button click
  - [x] add logic to display different button text 

## Complexity

L

**Comment by StefanFitoussi** [comment]
Really cool! :) Just some few typos:

Value Proposition:
"...I can change [the] information of a spot"

Acceptance Criteria:
"...has a[n] edit button"

 "...the edit button shows a[n] edit icon"
