### ISSUE TITLE
pages and routing

### ISSUE THREAD

**Issue by FelineHuhn** [FelineHuhn/capstone-project-parenthood#6]
## Value Proposition

**As a** user
**I want to** have the content sections in different pages 
**so that** I don't get overwhelmed by the amount of information

## Description

![Image](https://user-images.githubusercontent.com/112863528/203789723-53ee04e6-0f05-4eb2-9acb-4f6ac838b4d6.png)

## Acceptance criteria
- [x] the spot list section is on a separate spots page and is the landing page 
- [x] the create spot section is on a separate create page 
- [x] the edit spot section is on a separate edit page
- [x] each page has it's own headline

- On spots page:
  - [x] "Details" button will toggle between fold out the details section and fold in them
  - [x] "Neuen ParentHood Spot hinzufügen" button will navigate to create page
- In details section: 
  - [x] edit button will navigate to edit page
  - [x] delete button will navigate to spots page
  - [x] closing button will also fold in the details section
- On create page: 
  - [x] "Spot erstellen" button will navigate to spots page
  - [x] "Zurück" button will navigate to spots page
- On edit page: 
  - [x] "Spot aktualisieren" button will navigate to related details section in spots page
  - [x] "Zurück" button will navigate to related details section in spots page

## Tasks
- [x] create feature branch
- [x] create `spots` page
    - [x] add headline "ParentHood Spots"
    - [x] add Link to navigate to `create` page on click of "Neuen Parenthood Spot hinzufügen" button
    
- in details section:
    - [x] add Link to navigate to `spots` page on click of delete button
    - [x] add Link to navigate to `edit` page by on click of edit button
    - [x] add closing icon to cancel button
- [x] create `create` page 
    - [x] add headline "ParentHood Spot hinzufügen"
    - [x] add "Zurück" button
        - [ ] add Link to navigate to `spots` page on button click
    - [x] add Link to navigate to `spots` page on click of "Spot erstellen" button
- [x] create `edit` page
    - [x] add headline "ParentHood Spot bearbeiten"
    - [x] add "Zurück" button
        - [x] add Link to navigate to details section on button click
    - [x] add Link to navigate to details section on click of "Spot aktualisieren" button

## Complexity Estimation
L

**Comment by BucherLara** [comment]
Huhu Feline, your Wireframes look pretty good even though there is a lot going on, its very understandable especially together with the acceptance criteria. Why do you call the spot list section, section? It may be a little confusing because I thought they were already in different sections(pages). Maybe you can just call them: spot list, create new spots, etc? And maybe you can add the page name ... on a separate page **called spot list page***? If you like you can add the users perspective in the acceptance criteria: When the user clicks on the ...button ( but i dont think you need it).

**Comment by FelineHuhn** [comment]
Hey Lara, thank you for your feedback, i totally forgot to mention the headlines on the pages 🤣 so I added them to the wireframes, AC's and Task. 
Only the feedback for calling the sections "sections" i would prefer to retain the wording, because I don't define sections as pages but as segments.

**Comment by ahohnsen** [comment]
Hey Feline,

As Lara already mentioned, there is a lot going on in the wireframes and Acceptance Criteria 🙈 
I would suggest to structure the Acceptance Criteria a bit differently to make it easier understandable for others, e.g.:

- On spots page:
   - "Details" button will navigate to details page
   - "Neuen ParentHoodSpot hinzufügen" button on spots page will navigate to create page
- On the details page:
  - edit button will navigate to edit page
  - delete button will navigate to spots page
  - "Zurück" button will navigate to spots page
...

Additionally, I think it would be sufficient to write something generic like _"Each page has it's own headline"_ instead of mentioning every headline in the Acceptance Criteria. 🙂 

I think that would make it easier to read but it is just a personal preference. 💡
