### ISSUE TITLE
header and navigation

### ISSUE THREAD

**Issue by FelineHuhn** [FelineHuhn/capstone-project-parenthood#8]
## Value Proposition

**As a** user
**I want to** see a header and navigation
**so that** the application is even clearer and I can click through it faster

## Description

![Image](https://user-images.githubusercontent.com/112863528/202219213-a3a8e3e4-6c9e-44df-a164-8ccddac45cc3.png)

## Acceptance criteria

- [x] each page has a fixed header at the top
- [x] the header is displaying the headline of the page
- [x] each page has a fixed navigation at the bottom
- [x] the navigation has a spot icon and a create icon
    - [x] by clicking the spot icon the user will navigate to the spots page
    - [x] by clicking the add icon the user will navigate to the create page
 
## Tasks

- [x] create feature branch
- [x] create `Header` component
    - [x] add fixed header
- [x] create `Footer` component
    - [x] add fixed navigation
    - [x] add spot icon as Link
        - [x] add logic to link to spots page on click 
    - [x] add create icon as Link
        - [x] add logic to link to create page on click
- [x] remove "Neuen ParentHood Spot hinzufügen" button from spots page
- [x] remove "Zurück" button from create page
- [x] use `Header` component to display the header with corresponding headline on each page
- [x] remove previous headlines
- [x] use `Footer` component to display the navigation on each page

## Complexity

M

**Comment by gaiisay** [comment]
Looks good. Just a hint: Think about putting the Header and Navigation Components into a Layout Component so you don't have to insert them on every single page.
